apiVersion: v1
kind: Service
metadata:
  name: identity-app
  namespace: frontend
  labels:
    app: identity-app
spec:
  ports:
  - port: 80
  selector:
    app: identity-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-app
  namespace: frontend
  labels:
    app: identity-app
spec:
  selector:
    matchLabels:
      app: identity-app
  replicas: 1
  template:
    metadata:
      labels:
        app: identity-app
    spec:
      containers:
      - name: identity-app
        image: us-central1-docker.pkg.dev/sofisoft-lab/enterprise/identity-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-app
  namespace: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - accounts.sofisoft.pe
    secretName: accounts-tls
  rules:
  - host: accounts.sofisoft.pe
    http:
      paths:
      - path: /identity(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: identity-app
            port:
              number: 80